### ISSUE TITLE
Add shortcut to settings

### ISSUE THREAD

**Issue by bruno-garcia** [wmak/santry-trace-extension#2]
![image](https://user-images.githubusercontent.com/1633368/110139435-01e62a00-7da1-11eb-86c6-13e938c629fd.png)

Once I configured it, clicking on the extension shows me this ^ but there's no easily accessibly way to get back to the settings.

**Comment by wmak** [comment]
Will be fixed in https://github.com/wmak/santry-trace-extension/pull/3 where we won't need settings anymore 😄
